### 列表
GET http://localhost:8000/deploy
Content-Type: application/json

### 单个详情
GET http://localhost:8000/deploy/nginx-deployment-name01
Content-Type: application/json

### 从文件中创建deploy
POST http://localhost:8000/deploy
Content-Type: application/json

{
  "path": "/Users/rxt/Desktop/my/vagrant-k8s/src/demo02/yamls/nginx.yaml"
}

### 通过文件删除deploy
DELETE http://localhost:8000/deploy
Content-Type: application/json

{
  "path": "/Users/rxt/Desktop/my/vagrant-k8s/src/demo02/yamls/nginx.yaml"
}

### 增加/减少副本数量
POST http://localhost:8000/deploy-scale
Content-Type: application/json

// dec true减少 false增加
{
  "deployment_name": "nginx-deployment-name01",
  "dec": false
}